### ISSUE TITLE
ConcurrentModificationException in 0.4.13

### ISSUE THREAD

**Issue by CharlieTap** [Kotlin/kotlinx-benchmark#279] opened 2024-11-27 21:19 UTC
If I run ./gradlew benchmark I get a ConcurrentModificationException using 0.4.13.

Whats odd is that if I run jvmBenchmark or macosArm64Benchmark directly both work. If you need a reproduced simply checkout the latest version of [chasm](https://github.com/CharlieTap/chasm)

**Comment by fzhinkin** [comment] 2024-11-27 21:37
I was not able to reproduce the CME using the latest version of `chasm`. @CharlieTap could you please attach a stack trace?

**Comment by fzhinkin** [comment] 2024-12-02 17:09
@CharlieTap, thanks! Indeed, the issue is easily reproducible by invoking Gradle tasks from UI.

However, it seems like it has nothing to do with kotlinx-benchmarks update: one can get CME by running `:executor:build` from Idea; it is reproducible w/ `c22d2ed0270908654468fd8b48e11dcd9ce70a15` (the one, before version updates):
```
* What went wrong:
Error while saving task graph
> Configuration cache state could not be cached: field `provider` of `org.gradle.internal.serialize.codecs.core.ProviderBackedFileCollectionSpec` bean found in field `metadata` of `org.jetbrains.kotlin.gradle.plugin.mpp.SourceSetMetadataOutputs` bean found in field `value` of `org.jetbrains.kotlin.gradle.utils.LenientFutureImpl$Surrogate` bean found in field `sourceSetMetadataOutputs` of `org.jetbrains.kotlin.gradle.plugin.mpp.GranularMetadataTransformation$ProjectData` bean found in field `projectData` of `org.jetbrains.kotlin.gradle.plugin.mpp.GranularMetadataTransformation$Params` bean found in field `transformationParameters` of task `:libs:sse2:transformCommonMainDependenciesMetadata` of type `org.jetbrains.kotlin.gradle.plugin.mpp.MetadataDependencyTransformationTask`: error writing value of type 'org.gradle.api.internal.provider.TransformBackedProvider'
   > Could not create task ':libs:stack:compileMacosMainKotlinMetadata'.
      > java.util.ConcurrentModificationException (no error message)
> There are 7 more failures with identical causes.
```

**Comment by fzhinkin** [comment] 2024-12-03 20:33
@CharlieTap it seems like the issue is linked with parallel configuration cache being enable. At least, when disabled (`org.gradle.configuration-cache.parallel=false`), CME is not longer thrown.

**Comment by fzhinkin** [comment] 2024-12-03 20:55
The issue seems to be unrelated to `kotlinx-benchmarks`, so I'm closing it.

Feel free to reopen it if you believe that it's indeed caused by `kotlinx-benchmarks`.
If you suspect that the issue has something to do with Kotlin Gradle Plugin, please file a ticket in [Kotlin YouTrack](https://youtrack.jetbrains.com/issues/KT).

**Closed by fzhinkin** 2024-12-03 20:55 UTC
